server:
  port: 8080
  network:
    worker: 4
    expiration: 30
    outputBuffer: 1024
    recycler:
      initialCapacity: 64
      minimumCapacity: 64
      halfCollect: 256
      fullCollect: 512
      collectThreshold: 0.3
      collectRate: 0.5

  actor:
    worker: 8

player:
  queueBuffer: 1024
  recycler:
    initialCapacity: 64
    minimumCapacity: 64
    halfCollect: 256
    fullCollect: 512
    collectThreshold: 0.3
    collectRate: 0.5

service:
  core: []
  extend: []
  queueBuffer: 1024
  recycler:
    initialCapacity: 64
    minimumCapacity: 64
    halfCollect: 256
    fullCollect: 512
    collectThreshold: 0.3
    collectRate: 0.5